In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
X = pd.read_csv('Features.csv')
y = pd.read_csv('Label.csv')

In [3]:
X = X.iloc[:,1:].values
y = y.iloc[:,-1].values

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2])], remainder='passthrough')
X = ct.fit_transform(X).toarray()

In [5]:
print(X)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [24]:
param_grid = {'max_features': ['auto', 'sqrt'],
               'max_depth': [2,4],
               'min_samples_split': [2, 5],
               'min_samples_leaf': [1, 2],
               'splitter' : ['best', 'random']}

In [25]:
from sklearn.tree import DecisionTreeRegressor

regressor = DecisionTreeRegressor()

In [26]:
from sklearn.model_selection import GridSearchCV
rf_Grid = GridSearchCV(estimator = regressor, param_grid = param_grid, cv = 3, verbose=2, n_jobs = 4)

In [27]:
rf_Grid.fit(X_train, y_train)

Fitting 3 folds for each of 32 candidates, totalling 96 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  60 tasks      | elapsed:    1.4s
[Parallel(n_jobs=4)]: Done  96 out of  96 | elapsed:    1.7s finished


GridSearchCV(cv=3, estimator=DecisionTreeRegressor(), n_jobs=4,
             param_grid={'max_depth': [2, 4], 'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'splitter': ['best', 'random']},
             verbose=2)

In [28]:
rf_Grid.best_params_

{'max_depth': 4,
 'max_features': 'auto',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'splitter': 'best'}

In [33]:
regressor = DecisionTreeRegressor()
regressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [34]:
y_pred = regressor.predict(X_test)

In [35]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9333786884865058

In [13]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

258091.93333412096