In [21]:
import pandas as pd
import numpy as np


In [22]:
X = pd.read_csv('Features.csv')
y = pd.read_csv('Label.csv')

In [23]:
X = X.iloc[:,1:].values
y = y.iloc[:,-1].values

In [24]:
print(X)

[['None' '09:00:00' 'Tuesday']
 ['None' '10:00:00' 'Tuesday']
 ['None' '11:00:00' 'Tuesday']
 ...
 ['None' '21:00:00' 'Sunday']
 ['None' '22:00:00' 'Sunday']
 ['None' '23:00:00' 'Sunday']]


In [25]:
print(y)

[5545 4516 4767 ... 2159 1450  954]


In [26]:
print(X)

[['None' '09:00:00' 'Tuesday']
 ['None' '10:00:00' 'Tuesday']
 ['None' '11:00:00' 'Tuesday']
 ...
 ['None' '21:00:00' 'Sunday']
 ['None' '22:00:00' 'Sunday']
 ['None' '23:00:00' 'Sunday']]


In [27]:
print(y)

[5545 4516 4767 ... 2159 1450  954]


In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1,2])], remainder='passthrough')
X = ct.fit_transform(X).toarray()

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [30]:
from xgboost import XGBRegressor
regressor = XGBRegressor()
regressor.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=4, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [11]:
y_pred = regressor.predict(X_test)

In [12]:
print(y_pred)

[ 386.2151 6170.578  2983.273  ... 2718.3052 3627.1655 4785.5283]


In [13]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9333864299243853

In [14]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

258062.5902319507

In [15]:
a = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

In [16]:
a = pd.DataFrame(a)

In [17]:
a.head()

0       1
0   386.215088   501.0
1  6170.578125  6731.0
2  2983.272949  2865.0
3  5579.057129  1141.0
4  5940.690430  4578.0

In [18]:
a.to_csv('XGB1.csv')

In [19]:
y_pred.shape

(12173,)